<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CityGuide\Module'                        => __DIR__ . '/Module.php',
    'CityGuide\Controller\IndexController' => __DIR__ . '/src/CityGuide/Controller/IndexController.php',
    'CityGuideTest\Framework\TestCase'        => __DIR__ . '/tests/CityGuide/Framework/TestCase.php',
    'CityGuideTest\SampleTest'                => __DIR__ . '/tests/CityGuide/SampleTest.php',
);
