<?php
$this->headTitle('Delete Vacancy');
$url = $this->url('delete_vacancy',array(
    'action' => 'delete',
    'id'    => $this->id
))
?>
<h1><?php echo $this->escapeHtml($vacancy->nameEn); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($vacancy->nameEn); ?>'
    '<?php echo $this->escapeHtml($vacancy->nameAr); ?>'?
</p>
<form action="<?= $url ?>" method="post">
    <input type="hidden" name="id" value="<?php echo (int) $vacancy->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</form>