<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'RateCard\Module'                        => __DIR__ . '/Module.php',
    'RateCard\Controller\IndexController'    => __DIR__ . '/src/RateCard/Controller/IndexController.php',
    'RateCardTest\Framework\TestCase'        => __DIR__ . '/tests/RateCard/Framework/TestCase.php',
    'RateCardTest\SampleTest'                => __DIR__ . '/tests/RateCard/SampleTest.php',
);
