<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Career\Module'                        => __DIR__ . '/Module.php',
    'Career\Controller\IndexController' => __DIR__ . '/src/Career/Controller/IndexController.php',
    'TestTest\Framework\TestCase'        => __DIR__ . '/tests/Career/Framework/TestCase.php',
    'TestTest\SampleTest'                => __DIR__ . '/tests/Career/SampleTest.php',
);
