<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Authenticate\Module'                        => __DIR__ . '/Module.php',
    'Authenticate\Controller\IndexController' => __DIR__ . '/src/Authenticate/Controller/IndexController.php',
    'TestTest\Framework\TestCase'        => __DIR__ . '/tests/Test/Framework/TestCase.php',
    'TestTest\SampleTest'                => __DIR__ . '/tests/Test/SampleTest.php',
);
